databases:
  # 1. PostgreSQL Database Service
  - name: db
    plan: free
    postgres:
      version: 16

services:
  # 2. Django Backend Service
  - name: backend
    type: web
    plan: free
    runtime: python
    rootDir: backend # Set the context to the backend folder
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: CLIENT_URL
        value: https://montanha-viva-dashboard-frontend.onrender.com # WORKAROUND: Update this placeholder with your actual frontend URL after the first deploy. Render Blueprints can't get a static site's URL dynamically.

  # 3. React Frontend Service
  - name: frontend
    type: static
    plan: free
    rootDir: frontend # Set the context to the frontend folder
    buildCommand: pnpm install && pnpm run build
    staticPublishPath: dist # Path is relative to rootDir
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: backend
          property: url
