services:
  # 1. PostgreSQL Database Service
  - name: db
    type: pserv
    plan: free # Using free plan, you can change if needed
    postgres:
      version: 16

  # 2. Django Backend Service
  - name: backend
    type: web
    plan: free
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true # Render will generate a secure key for you
      - key: DEBUG
        value: false
      - key: CLIENT_URL
        value: https://frontend.onrender.com # WORKAROUND: Manually set URL. Render does not support dynamic URL from static sites in blueprints. You may need to update this value in the Render UI after the first deploy if the URL is different.

  # 3. React Frontend Service
  - name: frontend
    type: static
    plan: free
    buildCommand: pnpm install && pnpm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: backend
          property: url
