# Generated by Django 5.2.3 on 2025-07-02 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PointOfInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("distance_km", models.FloatField(help_text="Mesafe (km)")),
                (
                    "duration",
                    models.CharField(help_text="Süre, örn: 4 h 30 min", max_length=50),
                ),
                (
                    "route_type",
                    models.CharField(
                        choices=[("circular", "Circular"), ("linear", "Linear")],
                        max_length=10,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("Easy", "Easy"),
                            ("Medium", "Medium"),
                            ("Hard", "Hard"),
                        ],
                        max_length=10,
                    ),
                ),
                ("altitude_min_m", models.IntegerField(help_text="Minimum irtifa (m)")),
                (
                    "altitude_max_m",
                    models.IntegerField(help_text="Maksimum irtifa (m)"),
                ),
                (
                    "accumulated_climb_m",
                    models.IntegerField(help_text="Toplam tırmanış (m)"),
                ),
                (
                    "start_point_gps",
                    models.CharField(
                        blank=True,
                        help_text="Başlangıç noktası GPS koordinatları",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "interaction_fauna",
                    models.TextField(
                        help_text="Rota boyunca gözlemlenebilecek fauna hakkında bilgi."
                    ),
                ),
                (
                    "image_card",
                    models.ImageField(
                        help_text="Rota kartı için görsel", upload_to="routes_images/"
                    ),
                ),
                (
                    "image_map",
                    models.ImageField(
                        help_text="Rota haritası görseli", upload_to="routes_images/"
                    ),
                ),
                (
                    "gpx_file",
                    models.FileField(
                        blank=True,
                        help_text="GPX dosyası",
                        null=True,
                        upload_to="gpx_files/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "points_of_interest",
                    models.ManyToManyField(blank=True, to="routes.pointofinterest"),
                ),
            ],
        ),
    ]
