# Generated by Django 5.2.3 on 2025-06-30 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("distance_km", models.FloatField()),
                ("duration", models.CharField(max_length=50)),
                (
                    "route_type",
                    models.CharField(
                        choices=[("circular", "Circular"), ("linear", "Linear")],
                        default="circular",
                        max_length=50,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("Easy", "Easy"),
                            ("Medium", "Medium"),
                            ("Hard", "Hard"),
                        ],
                        default="Medium",
                        max_length=10,
                    ),
                ),
                ("altitude_min_m", models.IntegerField()),
                ("altitude_max_m", models.IntegerField()),
                ("accumulated_climb_m", models.IntegerField()),
                (
                    "start_point_gps",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description", models.TextField()),
                (
                    "image_card",
                    models.ImageField(
                        blank=True, null=True, upload_to="routes/images/cards/"
                    ),
                ),
                (
                    "image_map",
                    models.ImageField(
                        blank=True, null=True, upload_to="routes/images/maps/"
                    ),
                ),
                (
                    "gpx_file",
                    models.FileField(
                        blank=True, null=True, upload_to="routes/gpx_files/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PointOfInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points_of_interest",
                        to="routes.route",
                    ),
                ),
            ],
        ),
    ]
