# Generated by Django 5.2.3 on 2025-07-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0002_remove_route_interaction_fauna"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="accumulated_climb_m",
            field=models.IntegerField(help_text="Accumulated climb in meters"),
        ),
        migrations.AlterField(
            model_name="route",
            name="altitude_max_m",
            field=models.IntegerField(help_text="Maximum altitude in meters"),
        ),
        migrations.AlterField(
            model_name="route",
            name="altitude_min_m",
            field=models.IntegerField(help_text="Minimum altitude in meters"),
        ),
        migrations.AlterField(
            model_name="route",
            name="distance_km",
            field=models.FloatField(help_text="Distance in kilometers"),
        ),
        migrations.AlterField(
            model_name="route",
            name="duration",
            field=models.CharField(
                help_text="Duration, e.g., 4 h 30 min", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="gpx_file",
            field=models.FileField(
                blank=True,
                help_text="GPX file for the route",
                null=True,
                upload_to="gpx_files/",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="image_card",
            field=models.ImageField(
                help_text="Image for the route card", upload_to="routes_images/"
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="image_map",
            field=models.ImageField(
                help_text="Image of the route map", upload_to="routes_images/"
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="start_point_gps",
            field=models.CharField(
                blank=True,
                help_text="Start point GPS coordinates",
                max_length=100,
                null=True,
            ),
        ),
    ]
