# Generated by Django 5.2.3 on 2025-07-02 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="location",
            field=models.CharField(
                blank=True, help_text="e.g., 40.7128, -74.0060", max_length=255
            ),
        ),
    ]
