# Generated by Django 5.2.3 on 2025-06-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scientific_name",
                    models.CharField(
                        help_text="Scientific name of the plant.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "common_names",
                    models.TextField(
                        blank=True, help_text="Common names, separated by commas."
                    ),
                ),
                (
                    "images",
                    models.JSONField(
                        default=list, help_text="List of paths to images for the plant."
                    ),
                ),
                (
                    "interaction_fauna",
                    models.TextField(
                        blank=True,
                        help_text="Description of interaction with fauna.",
                        null=True,
                    ),
                ),
                (
                    "food_uses",
                    models.TextField(
                        blank=True, help_text="Description of food uses.", null=True
                    ),
                ),
                (
                    "medicinal_uses",
                    models.TextField(
                        blank=True,
                        help_text="Description of medicinal uses.",
                        null=True,
                    ),
                ),
                (
                    "ornamental_uses",
                    models.TextField(
                        blank=True,
                        help_text="Description of ornamental uses.",
                        null=True,
                    ),
                ),
                (
                    "traditional_uses",
                    models.TextField(
                        blank=True,
                        help_text="Description of traditional uses.",
                        null=True,
                    ),
                ),
                (
                    "aromatic_uses",
                    models.TextField(
                        blank=True, help_text="Description of aromatic uses.", null=True
                    ),
                ),
                (
                    "uses_flags",
                    models.JSONField(
                        default=dict,
                        help_text="Boolean flags for various uses (e.g., {'medicinal': true, 'food': false}).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Plant",
                "verbose_name_plural": "Plants",
                "ordering": ["scientific_name"],
            },
        ),
    ]
