# Generated by Django 5.2.3 on 2025-07-02 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scientific_name",
                    models.CharField(
                        help_text="Bilimsel ad, örn: Arbutus unedo",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "common_names",
                    models.CharField(
                        help_text="Yaygın adlar, virgülle ayrılmış, örn: Kocayemiş, Sandal Ağacı",
                        max_length=500,
                    ),
                ),
                (
                    "interaction_fauna",
                    models.TextField(
                        blank=True,
                        null=True,
                        help_text="Böcekler ve kuşlar için besin ve barınak kaynağıdır.",
                    ),
                ),
                ("food_uses", models.TextField(blank=True, null=True)),
                ("medicinal_uses", models.TextField(blank=True, null=True)),
                ("ornamental_uses", models.TextField(blank=True, null=True)),
                ("traditional_uses", models.TextField(blank=True, null=True)),
                ("aromatic_uses", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlantImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="flora_images/")),
                (
                    "plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="flora.plant",
                    ),
                ),
            ],
        ),
    ]
