# Generated by Django 5.2.3 on 2025-07-02 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userscannedqr',
            options={'verbose_name': 'User Scanned QR', 'verbose_name_plural': 'User Scanned QRs'},
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='code',
            field=models.CharField(help_text='The unique code for the discount coupon', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the coupon was created'),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='expires_at',
            field=models.DateTimeField(help_text='Expiration date and time of the coupon'),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='is_used',
            field=models.BooleanField(default=False, help_text='Indicates whether the coupon has been used'),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='points_spent',
            field=models.PositiveIntegerField(default=100, help_text='Points spent to obtain this coupon'),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='user',
            field=models.ForeignKey(help_text='The user who owns the coupon', on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the QR code was created'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='name',
            field=models.CharField(help_text='The name of the QR code (e.g., Main Entrance QR)', max_length=255),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='points',
            field=models.PositiveIntegerField(default=10, help_text='Points awarded when this QR code is scanned'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='qr_image',
            field=models.ImageField(blank=True, help_text='The generated QR code image', upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='text_content',
            field=models.CharField(help_text='The text or URL encoded in the QR code', max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='userscannedqr',
            name='qr_code',
            field=models.ForeignKey(help_text='The QR code that was scanned', on_delete=django.db.models.deletion.CASCADE, to='qr.qrcode'),
        ),
        migrations.AlterField(
            model_name='userscannedqr',
            name='scanned_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the QR code was scanned'),
        ),
        migrations.AlterField(
            model_name='userscannedqr',
            name='user',
            field=models.ForeignKey(help_text='The user who scanned the QR code', on_delete=django.db.models.deletion.CASCADE, related_name='scanned_qrs', to=settings.AUTH_USER_MODEL),
        ),
    ]
