# Generated by Django 5.2.3 on 2025-07-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="points",
            field=models.PositiveIntegerField(
                default=0, help_text="User's accumulated points for the reward system."
            ),
        ),
    ]
