# Generated by Django 5.2.3 on 2025-06-30 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="category",
            field=models.CharField(
                choices=[
                    ("general", "General Inquiry"),
                    ("bug", "Bug Report"),
                    ("feature", "Feature Request"),
                    ("other", "Other"),
                ],
                default="general",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="subject",
            field=models.CharField(max_length=200),
        ),
    ]
