# Generated by Django 5.2.3 on 2025-06-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_feedback_category_feedback_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="surname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
